"""add teacher offering slots and registration slot preferences

Revision ID: 07b32b4a2cef
Revises: 247158b1db1d
Create Date: 2026-03-24 01:09:34.446980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07b32b4a2cef'
down_revision = '247158b1db1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_offering_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('academic_year', sa.String(length=9), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('classroom_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('max_groups', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('day_of_week >= 1 AND day_of_week <= 7', name='check_offering_day_of_week'),
    sa.CheckConstraint('max_groups >= 1', name='check_offering_max_groups'),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_id', 'course_id', 'academic_year', 'day_of_week', 'start_time', 'end_time', name='uq_teacher_course_year_time')
    )
    op.create_table('registration_slot_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration_id', sa.Integer(), nullable=False),
    sa.Column('offering_slot_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.CheckConstraint('priority >= 1', name='check_slot_preference_priority'),
    sa.ForeignKeyConstraint(['offering_slot_id'], ['teacher_offering_slots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['registration_id'], ['course_registrations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_id', 'offering_slot_id', name='uq_registration_offering_slot'),
    sa.UniqueConstraint('registration_id', 'priority', name='uq_registration_slot_priority')
    )
    with op.batch_alter_table('course_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_offering_slot_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'teacher_offering_slots', ['source_offering_slot_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_groups', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('source_offering_slot_id')

    op.drop_table('registration_slot_preferences')
    op.drop_table('teacher_offering_slots')
    # ### end Alembic commands ###
