"""add course_teachers and refactor teacher relation

Revision ID: 38fbd58cdea2
Revises: dcb753e9a846
Create Date: 2025-11-14 17:03:54.026720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '38fbd58cdea2'
down_revision: Union[str, Sequence[str], None] = 'dcb753e9a846'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classrooms',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=50), nullable=False),
        sa.Column('capacity', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )

    op.create_table('informatics_blocks',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('course_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('skills', postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )

    op.drop_table('available_time_slots')

    op.add_column('course_registrations', sa.Column('block_id', sa.Integer(), nullable=True))
    op.add_column('course_registrations', sa.Column('skills', postgresql.ARRAY(sa.String()), nullable=True))
    op.create_foreign_key(None, 'course_registrations', 'informatics_blocks', ['block_id'], ['id'], ondelete='SET NULL')

    # -------------------------------
    # FIX use_classroom_capacity
    # -------------------------------
    op.add_column('courses', sa.Column('use_classroom_capacity', sa.Boolean(), nullable=True))
    op.execute("UPDATE courses SET use_classroom_capacity = FALSE")
    op.alter_column('courses', 'use_classroom_capacity', nullable=False)
    # -------------------------------

    op.add_column('schedule_slots', sa.Column('classroom_id', sa.Integer(), nullable=True))
    op.add_column('schedule_slots', sa.Column('block_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'schedule_slots', 'informatics_blocks', ['block_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'schedule_slots', 'classrooms', ['classroom_id'], ['id'], ondelete='SET NULL')

    op.drop_column('schedule_slots', 'classroom')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_slots', sa.Column('classroom', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'schedule_slots', type_='foreignkey')
    op.drop_constraint(None, 'schedule_slots', type_='foreignkey')
    op.drop_column('schedule_slots', 'block_id')
    op.drop_column('schedule_slots', 'classroom_id')
    op.drop_column('courses', 'use_classroom_capacity')
    op.drop_constraint(None, 'course_registrations', type_='foreignkey')
    op.drop_column('course_registrations', 'skills')
    op.drop_column('course_registrations', 'block_id')

    op.create_table('available_time_slots',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('day_of_week', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('start_time', postgresql.TIME(), autoincrement=False, nullable=False),
        sa.Column('end_time', postgresql.TIME(), autoincrement=False, nullable=False),
        sa.CheckConstraint('day_of_week >= 1 AND day_of_week <= 7', name=op.f('available_time_slots_day_of_week_check')),
        sa.PrimaryKeyConstraint('id', name=op.f('available_time_slots_pkey'))
    )

    op.drop_table('informatics_blocks')
    op.drop_table('classrooms')
    # ### end Alembic commands ###

