"""add course_teachers and refactor teacher relation

Revision ID: ce31c60401ae
Revises: 
Create Date: 2025-11-10 21:34:31.682883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ce31c60401ae'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_teachers',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('course_id', 'teacher_id')
    )
    op.drop_constraint(op.f('course_registrations_student_id_course_id_key'), 'course_registrations', type_='unique')
    op.create_unique_constraint('unique_student_course', 'course_registrations', ['student_id', 'course_id'])
    op.drop_column('course_registrations', 'completed')
    op.drop_column('course_registrations', 'completed_at')
    op.drop_constraint(op.f('courses_teacher_id_fkey'), 'courses', type_='foreignkey')
    op.drop_column('courses', 'teacher_id')
    op.alter_column('students', 'enrolled_this_year',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'enrolled_this_year',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.add_column('courses', sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('courses_teacher_id_fkey'), 'courses', 'teachers', ['teacher_id'], ['id'], ondelete='SET NULL')
    op.add_column('course_registrations', sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('course_registrations', sa.Column('completed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.drop_constraint('unique_student_course', 'course_registrations', type_='unique')
    op.create_unique_constraint(op.f('course_registrations_student_id_course_id_key'), 'course_registrations', ['student_id', 'course_id'], postgresql_nulls_not_distinct=False)
    op.drop_table('course_teachers')
    # ### end Alembic commands ###
